apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-app
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
      - name: restaurant-app
        image: restaurant-app:latest
        ports:
        - containerPort: 5005
        env:
          - name: DB_HOST
            value: host.minikube.internal
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: Root@123
          - name: DB_NAME
            value: testproject
          - name: DB_PORT
            value: "3306"